### ISSUE TITLE
请问有计划支持开放平台吗？

### ISSUE THREAD

**Issue by bugstark** [ArtisanCloud/PowerWeChat#118]
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/getting_started/terminology_introduce.html

**Comment by Matrix-X** [comment]
谢谢你的问题，开放平台的确我们在考虑，能列一下你觉得比较迫切重要的模块，我们可以排序，不断迭代上去

**Comment by bugstark** [comment]
个人认为开放平台可以有效复用产品，实现价值最大化，基于开放平台可以管理多个公众号/小程序
比如可以 NewOfficialAccountByOplatform(AppID string) (*OfficialAccount, error) {}
目前我们的痛点在多个公众号在不同系统中的应用，目前采用的方式是用开放平台统一管理，提供 accesstoken 管理接口，既满足多个账号共用，又不会因为多点刷新token造成异常，目前系统是基于其他语言构建，不太方便贡献代码
其实开放平台除了绑定账号、全网发布等API，其他API大部分可以和公众号/小程序共用

**Comment by Matrix-X** [comment]
好的，我们团队商量一次

**Comment by Matrix-X** [comment]
如果可以，请到github首页，扫我们的微信公众号，我们在群里讨论一下开发计划。谢谢

**Comment by Matrix-X** [comment]
如果进群，请报一下你是bugstark
