### ISSUE TITLE
有计划集成微信“一物一码”接口吗？

### ISSUE THREAD

**Issue by johnshi** [ArtisanCloud/PowerWeChat#121]
https://developers.weixin.qq.com/doc/offiaccount/Unique_Item_Code/Unique_Item_Code_API_Documentation.html

**Comment by Matrix-X** [comment]
你好，谢谢你的反馈，这个排期可能会比较靠后，暂时会没时间关注在这里，如果你有迫切的需求，可以欢迎提PR
