### ISSUE TITLE
小程序直播接口参数和返回类型增加

### ISSUE THREAD

**Issue by WalleV** [ArtisanCloud/PowerWeChat#13]
### 问题原因：

由于[微信小程序直播](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/livebroadcast/liveBroadcast.createRoom.html)部分存在文档缺陷，所有接口都是相同的传参和返回值。

例如： 
- [https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/livebroadcast/liveBroadcast.addAssistant.html](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/livebroadcast/liveBroadcast.addAssistant.html)
- [https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/livebroadcast/liveBroadcast.addGoods.html](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/livebroadcast/liveBroadcast.addGoods.html)
- [https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/livebroadcast/liveBroadcast.addGoods.html](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/livebroadcast/liveBroadcast.addGoods.html)

等页面中，文档都是一样的，只是api名字换了一下。 

### 解决办法：
微信的直播文档在平台能力那边，所以需要重新根据[小程序直播](https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/industry/liveplayer/live-player-plugin.html)里面的文档重新封装sdk。

**Comment by Matrix-X** [comment]
refact in feature/work
"refactor(work) - broadcast request and response"
