### ISSUE TITLE
2.0版本初始化报错

### ISSUE THREAD

**Issue by RipperTs** [ArtisanCloud/PowerWeChat#142]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/43734404/182769592-0ed4b9eb-ce3e-4240-82f3-d013b6ed8f47.png">

<img width="958" alt="image" src="https://user-images.githubusercontent.com/43734404/182769624-cc9e0a88-a1cd-4655-b457-469a947d5c9e.png">

**Comment by Matrix-X** [comment]
请升级到最新的版本，beta9太久了，这个我们已经更新过使用了，最新的是beta38

**Comment by Matrix-X** [comment]
也欢迎来到我们的企业微信群，我们里面的小伙伴也可以帮你回答很多使用上的问题
