### ISSUE TITLE
公众号获取用户基础信息有问题

### ISSUE THREAD

**Issue by sohenk** [ArtisanCloud/PowerWeChat#153]
我用.OAuth.UserFromCode可以成功调用，但是当我用对应的GetAccessToken,或者getopenid都获取不到对应的值

**Comment by Matrix-X** [comment]
请展示一下问题的主要代码，以及sdk的版本。

如果方便，请加入我们我们的企业微信群，沟通会更便捷。

**Comment by sohenk** [comment]
> 

企业微信群满了加不进去

**Comment by sohenk** [comment]
> 请展示一下问题的主要代码，以及sdk的版本。
> 
> 如果方便，请加入我们我们的企业微信群，沟通会更便捷。

企业微信群满了，加不进去。我发现问题是scope无法修改

**Comment by Matrix-X** [comment]
我来操作你的pull request，感谢
