### ISSUE TITLE
生成小程序二维码接口WXACode.GetUnlimited参数中的特殊字符问题

### ISSUE THREAD

**Issue by beijibeijing** [ArtisanCloud/PowerWeChat#167]
小程序本身接口是支持部分特殊字符的"最大32个可见字符，只支持数字，大小写英文以及部分特殊字符：!#$&'()*+,/:;=?@-._~，其它字符请自行编码为合法字符（因不支持%，中文无法使用 urlencode 处理，请使用其他编码方式）"
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/qr-code/wxacode.getUnlimited.html#method-http.

但是WXACode.GetUnlimited中scene传参带特殊字符，调用微信接口时会被转义导致微信报40129错误

**Comment by WalleV** [comment]
@beijibeijing 

这个是属于golang json本身会强制替换html编码字符导致的，参考： https://pkg.go.dev/encoding/json
``` 
String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. So that the JSON will be safe to embed inside HTML <script> tags, the string is encoded using HTMLEscape, which replaces "<", ">", "&", U+2028, and U+2029 are escaped to "\u003c","\u003e", "\u0026", "\u2028", and "\u2029". This replacement can be disabled when using an Encoder, by calling SetEscapeHTML(false). 
```

虽然后面开放了SetEscapeHTML(false)关闭这类行为，但是由于我们底层用的http client [gout](https://github.com/guonaihong/gout)没开放出来，导致一直存在强制转义的行为（本身这类转义是没有问题的，大部分web server框架都能正常读取。 碰巧微信的这个接口硬是去读原始值就出问题了😂）。**所以我们的解决方案就是不用特殊字符，只包含字母数字下划线之类的。**

我们也在等gout能够解决这个[issue](https://github.com/guonaihong/gout/issues/331)

**Comment by Matrix-X** [comment]
@beijibeijing 我们也有用户在群里提出了这个问题，如果你还没进群，欢迎进群，够用会更高效

https://github.com/ArtisanCloud/PowerWeChat/blob/release/2.0.0/resource/assets/contact_me_qr.png

**Comment by beijibeijing** [comment]
明白了~已加群谢谢

**Comment by Matrix-X** [comment]
We will fix it on Release 3.0

**Comment by guonaihong** [comment]
@Matrix-X @WalleV  新加了SetJSONNotEscape接口，和SetJSON类似，不转义HTML里面特殊字符。v0.3.3版本

**Comment by Matrix-X** [comment]
Please check v3.0.38
