### ISSUE TITLE
请问有公众号模板消息发送吗？

### ISSUE THREAD

**Issue by stone009** [ArtisanCloud/PowerWeChat#168]
看下了文档好像没有找到，大概什么时候上线这个功能呢

**Comment by Matrix-X** [comment]
https://github.com/ArtisanCloud/PowerWeChat/blob/release/2.0.0/src/officialAccount/templateMessage/client.go
功能应该有，我们应该还没放到文档里。你可以看一下

https://powerwechat.artisan-cloud.com/zh/mini-program/uniform-message.html
统一模版消息，支持小程序和公众号

**Comment by WalleV** [comment]
@stone009 

公众号模版消息文档已经增加，PowerWeChat保持当前版本无需更新。

如果发送模版，可以和小程序共用统一服务消息，我们这边发送都是可以的。

有问题随时联系我们，感谢！

文档： [https://powerwechat.artisan-cloud.com/zh/official-account/template-message.html](https://powerwechat.artisan-cloud.com/zh/official-account/template-message.html)
