### ISSUE TITLE
生成JSSDK参数报错

### ISSUE THREAD

**Issue by kasimchen** [ArtisanCloud/PowerWeChat#173]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/19259888/190856165-c5b1fa38-5f19-4127-a59e-b9556fb5e407.png">

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/19259888/190856204-db69308a-41fb-42aa-8313-d6974e14c95b.png">

**Comment by kasimchen** [comment]
第一次调用生成参数成功,第二次再调用就报错了

**Comment by Matrix-X** [comment]
请升级到最新版本，谢谢！
