### ISSUE TITLE
请问是否支持小程序新版获取手机号

### ISSUE THREAD

**Issue by RayCssjmt** [ArtisanCloud/PowerWeChat#175]
请问是否支持小程序新版获取手机号

**Comment by WalleV** [comment]
@RayCssjmt 文档里面已经有了。

https://powerwechat.artisan-cloud.com/zh/mini-program/user-info.html#%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E6%89%8B%E6%9C%BA%E5%8F%B7
