### ISSUE TITLE
Transfer.QueryBalanceOrder 查询问题

### ISSUE THREAD

**Issue by logan-liang** [ArtisanCloud/PowerWeChat#182]
Question：

调用 Transfer.QueryBalanceOrder 查询抛出异常，代码为：

`panic: reflect: call of reflect.Value.IsNil on bool value`

**Comment by logan-liang** [comment]
解决办法：更新至最新tag版本

**Comment by Matrix-X** [comment]
Thx for your issue, pls check @v2.0.16
