### ISSUE TITLE
在发布微信菜单，url中含有了&符号，会被转义为\u0026，导致发布失败

### ISSUE THREAD

**Issue by itzj86** [ArtisanCloud/PowerWeChat#189]
在发布微信菜单，url中含有了&符号，会被转义为\u0026，导致发布失败；
{
    "errcode": 40033,
    "errmsg": "invalid charset. please check your request, if include \\uxxxx will create fail! rid: 6351f0e3-4fa90897-25a38569"
}
然后用http.Post原始的请求发布，并没有这种问题，通过调试，发现是因为请求中json编码后会有这个问题存在。
感谢官方提供这么好用的库。也希望能解决这个bug

**Comment by Matrix-X** [comment]
https://github.com/ArtisanCloud/PowerWeChat/issues/167

请查看这个issue，应该是同一个问题

**Comment by itzj86** [comment]
好的。谢谢
