### ISSUE TITLE
微信菜单的struct 缺少Url属性，一级菜单也有可能是view类型，有url这个字段

### ISSUE THREAD

**Issue by itzj86** [ArtisanCloud/PowerWeChat#190]
type Button struct {
	Type       string      `json:"type,omitempty"`
	Name       string      `json:"name"`
	Key        string      `json:"key,omitempty"`
	SubButtons []SubButton `json:"sub_button,omitempty"`
}
因为没有url，导致发布菜单时被提示button url size ；不用库的这种方式接收数据，通过http.Post组装数据发送一切正常。
type Button struct {
	Type       string      `json:"type,omitempty"`
	Name       string      `json:"name"`
	Key        string      `json:"key,omitempty"`
	URL        string      `json:"url,omitempty"`   #添加这个后，发布菜单成功
	SubButtons []SubButton `json:"sub_button,omitempty"`
}

**Comment by Matrix-X** [comment]
请把你新增的代码提交一个 pull request，我来发布一下，谢谢

**Comment by itzj86** [comment]
好的。&nbsp;


言嘚菋道
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 上午10:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ArtisanCloud/PowerWeChat] 微信菜单的struct 缺少Url属性，一级菜单也有可能是view类型，有url这个字段 (Issue #190)





 
请把你新增的代码提交一个 pull request，我来发布一下，谢谢

**Comment by Matrix-X** [comment]
Thx for your PR, pls checkout version at v2.0.21
