### ISSUE TITLE
query参数被改变了

### ISSUE THREAD

**Issue by zhoushun5678** [ArtisanCloud/PowerWeChat#197]
POST /wxa/generate_urllink?access_token=62_qSoBD 
HTTP/1.1
> Content-Type: application/json
>
{
    "cloud_base": null,
    "env_version": "release",
    "expire_interval": 1668158616,
    "expire_type": 1,
    "path": "pages/storedata/index",
    "query": "FA=FAF\u0026mini_card_id=123"
}

{
    "errcode": 40212,
    "errmsg": "invalid query rid: 636e146b-3b26fb4a-11dfc7b4"
}

原始query：FA=FAF&mini_card_id=123

**Comment by Matrix-X** [comment]
https://github.com/ArtisanCloud/PowerWeChat/issues/167

请查看这个issue，应该是同一个问题
