### ISSUE TITLE
请问 access_token  token 似乎不会刷新吗 使用的是小程序的 获取手机号码方法

### ISSUE THREAD

**Issue by RayCssjmt** [ArtisanCloud/PowerWeChat#200]
MiniProgramApp.PhoneNumber.GetUserPhoneNumber(code)

{
"errcode": 40001,
"errmsg": "invalid credential, access_token is invalid or not latest rid: 63763df8-7be20627-34978741"
}

**Comment by Matrix-X** [comment]
这种问题最有可能是你用了应用集群部署，如果是应用集群，就要单独部署一个redis中控，否则每个应用单独一个redis，token会被冲掉

具体可以在加我们的微信群，具体沟通

**Comment by RayCssjmt** [comment]
感谢，明白了

**Comment by RayCssjmt** [comment]
感谢，明白了
