### ISSUE TITLE
小程序的条码/二维码识别的API 调用的微信url 写错了

### ISSUE THREAD

**Issue by zhangruzhao** [ArtisanCloud/PowerWeChat#221]
`// 本接口提供基于小程序的条码/二维码识别的API
// https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/img/img.scanQRCode.html
func (comp *Client) ScanQRCode(imgURL string, img *power.HashMap) (*response.ResponseIMGScanQRCode, error) {

	result := &response.ResponseIMGScanQRCode{}

	_, err := comp.UploadImage("cv/img/aicrop", imgURL, img, result)

	return result, err

}`

url应该是 'cv/img/qrcode'

**Comment by Matrix-X** [comment]
Please review https://github.com/ArtisanCloud/PowerWeChat/issues/167
We will fix it on Release 3.0
