### ISSUE TITLE
希望增加对企微bot接收消息的支持

### ISSUE THREAD

**Issue by ColinTree** [ArtisanCloud/PowerWeChat#222]
不过官方的企微bot文档很不完善，只有每个bot点进去那一页，讲推送消息的方法…
接收消息基本没文档
比如message_type除了text和mixed，还能为event，此时event.event_type可能为：
- enter_chat：用户进入bot私聊
- add_to_chat：bot被拉群

全网找不到，这俩还是自己试出来的

**Comment by Matrix-X** [comment]
谢谢你的问题，这开源项目，有些文档来不及更新
希望你可以加我企业微信，我看看怎么把这个问题对应的文档补齐，谢谢！

**Comment by ColinTree** [comment]
1. 我是指官方bot相关的文档不完善啦，比如我列举的那部分都没有提及，得靠自己试
2. 然后希望PowerWeChat的服务端能增加对bot的支持~

**Comment by Matrix-X** [comment]
如果官网的文档不完善，的确挺痛苦的。你们这个场景需求如果很强的话，可以企业微信聊一下。我们现在在排期弄新的版本

**Comment by ColinTree** [comment]
加群了，我们目前用python的fastapi自己写了一版bot服务器（独立的）
但对于我们来说语言无所谓，python不是必须的，所以冲浪过程看到你们这个项目~
