### ISSUE TITLE
微信公众号Access_token不支持并发

### ISSUE THREAD

**Issue by lemon-1997** [ArtisanCloud/PowerWeChat#244]
看了下代码，有重试刷新token机制，如果并发，是不是会重复顶掉之前的token（第一次拿token并发也会出现）。能否抽象Acess_token，调用方自己实现逻辑。
类似下面的代码
```go
type AccessToken interface {
    GetAccessToken() (accessToken string, err error)
    RefreshAccessToken(accessToken string) (accessToken string, err error)
}
```

**Comment by Matrix-X** [comment]
我们晚点试试，谢谢你的提问，欢迎加入我们的企业微信群，一起讨论，谢谢

**Comment by Matrix-X** [comment]
你好，Lemon，请试一下这个方法

services.MiniProgramApp.AccessToken.Refresh()

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/317570/212346233-22872afc-b1f5-484b-a0ce-97c4934e5978.png">

**Comment by lemon-1997** [comment]
> 你好，Lemon，请试一下这个方法
> 
> services.MiniProgramApp.AccessToken.Refresh()
> 
> <img alt="image" width="1246" src="https://user-images.githubusercontent.com/317570/212346233-22872afc-b1f5-484b-a0ce-97c4934e5978.png">

你好，这个方法没看到有加锁的逻辑，如果是并发的情况，重复调用微信的接口，上一个token就会失效。我刚看到代码有抽象access_token，但是好像没有方法取替换
```go
type (
	AccessTokenInterface interface {
		GetToken(refresh bool) (resToken *response2.ResponseGetToken, err error)
		Refresh() AccessTokenInterface
		ApplyToRequest(request *http.Request, requestOptions *object.HashMap) (*http.Request, error)
        } 
)
```
这是公众号的access_token
```go
type OfficialAccount struct {
	*kernel.ServiceContainer

	Base        *base.Client
	AccessToken *auth.AccessToken
       .......
}
type AccessToken struct {
	*kernel.AccessToken
}
```

**Comment by Matrix-X** [comment]
请加企业微信沟通这个问题，谢谢！

**Comment by ydedev** [comment]
请问下老哥解决了吗，这个问题

**Comment by Matrix-X** [comment]
> 请问下老哥解决了吗，这个问题

请用最新的版本，token有自动刷新的功能，同时也增加了token存储和读取可以重载接口
