### ISSUE TITLE
怎么判断指针类型是否存在？

### ISSUE THREAD

**Issue by chenxi2015** [ArtisanCloud/PowerWeChat#245]
MiniProgramApp.Auth.Session 返回的errcode不存在 直接通过err判断不了 errcode不为0的情况

```
session, err := s.MiniProgramApp.Auth.Session(ctx.Request.Context(), reqParams.Code)
if err != nil {
return nil, err
}
if session.ErrCode != 0 {
     return nil, errors.New(session.ErrMsg)
}
```

session.ErrCode 判断报错 请问怎么解决啊？

**Comment by Matrix-X** [comment]
没太理解你的意思，err是肯定判断不了errCode你可以加企业微信，我帮你开聊天窗口看看

**Comment by chenxi2015** [comment]
> 没太理解你的意思，err是肯定判断不了errCode你可以加企业微信，我帮你开聊天窗口看看

已经解决了 谢谢
