### ISSUE TITLE
v3 api接口部分请求方法错误

### ISSUE THREAD

**Issue by FourLeafTec** [ArtisanCloud/PowerWeChat#256]
微信支付v3 api对请求方法有强制要求,如两个查询订单接口,微信接口要求使用GET方法

当前client中使用[POST](https://github.com/ArtisanCloud/PowerWeChat/blob/8eea4da6b66fecea86ecd22c092334c508648b83/src/payment/order/client.go#L139)发起查询,微信返回405 Method not allowed

**Comment by Matrix-X** [comment]
谢谢，我晚些会查看，做响应调整

**Comment by FourLeafTec** [comment]
另外问个题外话v2接口还在维护么？
v2版微信支付中的撤单接口似乎调用的是v1的接口

**Comment by Matrix-X** [comment]
v2接口可以维护，我们底层请求是分微信支付v2和v3的不同请求接口，所以你可以加我企业微信或者微信群，我们可以高效沟通这些问题

**Comment by Matrix-X** [comment]
Please check v3.0.8

修正了查询v3订单接口的method
