### ISSUE TITLE
PR:Fix Refund query with http GET

### ISSUE THREAD

**Issue by FourLeafTec** [ArtisanCloud/PowerWeChat#267]
退款查询接口要求GET方法：[查询单笔退款API](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_10.shtml)

see PR：#266

**Comment by Matrix-X** [comment]
Thx, PR has been merged, I will make a release version later.

**Comment by Matrix-X** [comment]
pls check v3.0.13
