### ISSUE TITLE
微信公众号网页授权问题疑惑

### ISSUE THREAD

**Issue by TahmLi** [ArtisanCloud/PowerWeChat#268]
经过测试：
前端获取code使用https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx4371973ec8f9fa2a&redirect_uri=https://www.artisan-cloud.com&response_type=code&scope=snsapi_base&state=123#wechat_redirect时raw返回"errcode\":48001,\"errmsg\":\"api unauthorized“，access_token有值，appid无值
如果scope=snsapi_userinfo，一切正常（但是对于用户来说比静默授权多了一步授权行为）
还继续完善么

**Comment by Matrix-X** [comment]
let me check

**Comment by Matrix-X** [comment]
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/317570/222769487-4875f0a7-fb9e-4d84-a38f-6485c762c071.png">

这是我调试的过程，没有出现你这个问题。

如果可以请加企业微信沟通，这是最高效的方式

**Comment by Matrix-X** [comment]
又或者你可以把你完整的代码，让我看一下你是怎么出现这个问题的

**Comment by TahmLi** [comment]
找到了原因。前端使用snsapi_base，但后台直接使用了UserFromCode，才出现了api unauthorized问题
