### ISSUE TITLE
redis设置有没有集群模式

### ISSUE THREAD

**Issue by sixniu** [ArtisanCloud/PowerWeChat#281]
我们线上是redis是集群模式的，现在按照文档上的配置redis会报redis错误，MOVED 3367 
`Cache: kernel.NewRedisClient(&kernel.RedisOptions{
				Addr:     powerWechatParam.Redis.Host,
				Password: powerWechatParam.Redis.Pass,
				DB:       0,
			}),`

**Comment by Matrix-X** [comment]
这个是redis的报错，请先确保你本地的redis能正常使用。

**Comment by Matrix-X** [comment]
v3.1.22 支持RedisCluster，初始化redis稍微有点改动，文档已更新
