### ISSUE TITLE
公众号被动回复用户消息返回xml格式问题

### ISSUE THREAD

**Issue by xiaoyezzf** [ArtisanCloud/PowerWeChat#282]
# 这是微信文档里面的
![1680513454328](https://user-images.githubusercontent.com/20514637/229467403-f095ee58-4f55-4825-b67b-15e5c0da5fcf.jpg)
# 这是使用微信公众平台接口调试工具返回的
![image](https://user-images.githubusercontent.com/20514637/229467830-f8f7877d-1296-4f4f-b672-589e70bda6f2.png)
# 这是格式化之后的
![image](https://user-images.githubusercontent.com/20514637/229467961-62c86f84-95e5-4675-ae61-9e1f6871fb3e.png)

# 使用的代码是:
messages.NewImage(mediaId, &power.HashMap{})
微信公众号提示该公众号提供的服务出现故障, 请稍后再试

请问下这是bug还是没有使用正确

**Comment by xiaoyezzf** [comment]
这是回复图片的结果上面那个是回复视频 但是都有同样的问题 出了回复文本应该都有这个问题
![image](https://user-images.githubusercontent.com/20514637/229469561-35be6bee-068e-49a3-baf2-111cad610514.png)

**Comment by Matrix-X** [comment]
thx for your issue, pls check v3.0.22
