### ISSUE TITLE
标准的  MiniProgramApp.Encryptor.DecryptData() 存在bug

### ISSUE THREAD

**Issue by wensenz** [ArtisanCloud/PowerWeChat#284]
Cannot assign *support.CryptError to err (type error) in multiple assignment Type does not implement 'error' as some methods are missing: Error() string

标准的  MiniProgramApp.Encryptor.DecryptData() 存在bug

**Comment by Matrix-X** [comment]
应该是Error的类型的问题，你的err变量是常规的error变量，而这个函数返回的是， *support.CryptError

<img width="943" alt="image" src="https://user-images.githubusercontent.com/317570/229792176-88526e04-30dd-45a3-a9bd-05f7eff00dd3.png">

**Comment by Matrix-X** [comment]
朋友，我先暂时close掉这个issue，这个应该不是bug，我们现在项目都在跑这个方法，如果你还未解决，可以添加企业微信和我们沟通解决。
