### ISSUE TITLE
click事件是大写的

### ISSUE THREAD

**Issue by san-all** [ArtisanCloud/PowerWeChat#286]
src/officialAccount/server/handlers/models/event.go中的CALLBACK_EVENT_CLICK是小写的，微信发过来的click是全大写
![2023-04-08_22-37](https://user-images.githubusercontent.com/10701188/230727077-8db1db16-baf3-4da9-96dc-ed5660699420.png)
![2023-04-08_22-37_1](https://user-images.githubusercontent.com/10701188/230727121-c3248e5c-3dc7-490e-ac8e-a238f910de5c.png)

**Comment by Matrix-X** [comment]
Thx for your issue, pls check v3.0.23

I have also reviewed these events in the links  listed below:

https://developers.weixin.qq.com/doc/offiaccount/Custom_Menus/Custom_Menu_Push_Events.html
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Receiving_event_pushes.html
