### ISSUE TITLE
下单没有服务商模式？可以添加下不

### ISSUE THREAD

**Issue by daniel110119** [ArtisanCloud/PowerWeChat#288]
微信文档 https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter4_1_1.shtml

**Comment by Matrix-X** [comment]
这个可以添加，但是暂时全部的partner没太多时间可以完成，你可以列举几个接口，然后我把这个partner的子模块加上。

**Comment by Matrix-X** [comment]
请使用 v3.0.25 ，

https://powerwechat.artisan-cloud.com/zh/payment/partner.html

feature:

- 增加了服务商平台的支付支付功能
- 增加了公众号的草稿和发布文章接口
- 添加了公众号的发送文章

可以直接查看代码：
```go
response, err := services.PaymentApp.Partner.JSAPITransaction(ctx,options)

```
