### ISSUE TITLE
企微群机器人素材上传功能建议完善

### ISSUE THREAD

**Issue by sunyata686** [ArtisanCloud/PowerWeChat#290]
官方文档url如下：https://developer.work.weixin.qq.com/document/path/91770#%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8E%A5%E5%8F%A3
PowerWechat截图如下
![image](https://user-images.githubusercontent.com/68532326/230920998-5c1d329c-c282-4849-a57a-3dbc8204dcaa.png)

**Comment by Matrix-X** [comment]
noted，will check later

**Comment by Matrix-X** [comment]
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/317570/231116394-a257b123-3405-4445-8341-5c8337fb24cf.png">

我看了一下，接口有，请看图，但是文档应该没放上去
我晚点有一个新版本，把文档一起更新一下

**Comment by Matrix-X** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/317570/231240657-70bf24af-5562-4d4c-9231-f17d099bf919.png">
 
文档已更新

otherwise:

v3.0.25 
feature:

- 增加了服务商平台的支付支付功能
- 增加了公众号的草稿和发布文章接口
- 添加了公众号的发送文章
