### ISSUE TITLE
模板消息的问题

### ISSUE THREAD

**Issue by 256mywind** [ArtisanCloud/PowerWeChat#295]
OfficialAccountApp.TemplateMessage.Send(ctx, &request.RequestTemlateMessage{....

这里的ctx  我用context.Context 不对 说是这一个nil 然后我用 iris.Context 类型又不对。 这个地方要怎么填。

**Comment by Matrix-X** [comment]
请参考代码，如果没搞定，可以扫我们二维码群，直接企业微信中，帮助解决。
https://github.com/ArtisanCloud/PowerWechatTutorial

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/317570/233596213-8abef554-8758-4351-b90f-ce228ebfaab1.png">

**Comment by 256mywind** [comment]
你这个是gin 框架？ 我是用的iris  两个的context 上下文  不一样么？

**Comment by 256mywind** [comment]
解决了！

**Comment by Matrix-X** [comment]
ok, let me close this issue window
