### ISSUE TITLE
企业微信代开发

### ISSUE THREAD

**Issue by Kline-x** [ArtisanCloud/PowerWeChat#297]
请问支持企业微信代开发应用吗？

**Comment by Matrix-X** [comment]
感谢你的issue，感觉你现在很focus在企业微信开放平台和代开发这块

其实我们有做了这个openwork模块
<img width="458" alt="image" src="https://user-images.githubusercontent.com/317570/234164519-8a8c35ca-15d0-43b0-9492-ae05d50a6ec7.png">

但是因为我们暂时缺少测试环境去最终发布这个版本

处于现在我们手上有其他重要的项目要赶着出来，所以openwork的模块会在排期上。

Here is the roadmap we are working on:

- PowerX 1.0
  - crm (in develop)
  - scrm (in develop)
- AIPrompt (depend on RobotChat)
- RobotChat
  - OpenAI (in develop)
  - Midjounery (in develop)
- PowerWechat
  - OpenWork (pending)
  - MiniGame (pending)
