### ISSUE TITLE
bug get request is post？？？

### ISSUE THREAD

**Issue by zy84338719** [ArtisanCloud/PowerWeChat#302]
https://developers.weixin.qq.com/doc/offiaccount/Custom_Menus/Deleting_Custom-Defined_Menu.html

https://github.com/ArtisanCloud/PowerWeChat/pull/301

**Comment by Matrix-X** [comment]
👍 pls check [v3.0.28](https://github.com/ArtisanCloud/PowerWeChat/releases/tag/v3.0.28)

It must be replaced when we upgraded v2->v3.

thank you for you help!
