### ISSUE TITLE
PowerWechatTutorial services.WeComApp Config有问题

### ISSUE THREAD

**Issue by yg7001** [ArtisanCloud/PowerWeChat#308]
[PowerWechatTutorial](https://github.com/ArtisanCloud/PowerWechatTutorial/blob/master/controllers/wecom/oauth-controller.go) 16行
services.WeComApp.GetConfig().GetString("oauth.callback","")
获取不到配置内容，
经跟踪，配置项目应该是"oauth.callbacks"

**Comment by Matrix-X** [comment]
yes , you r right, pls check the release/v3.0.0 or develop branch

https://github.com/ArtisanCloud/PowerWechatTutorial
