### ISSUE TITLE
你好，服务商支付接口的支付者的openid写错了

### ISSUE THREAD

**Issue by zlei669** [ArtisanCloud/PowerWeChat#315]
服务商支付接口的支付者的openid有问题，具体位置是payment/partner/request/jsspi.go文件中的JSAPIPayer
应该是：
type Payer struct {
	// 用户在服务商AppID下的唯一标识。
	SpOpenid *string `json:"sp_openid,omitempty"`
	// 用户在子商户AppID下的唯一标识。
	SubOpenid *string `json:"sub_openid,omitempty"`
}

还有请修改下文件名jsspi.go为jsapi.go
谢谢

**Comment by zlei669** [comment]
现在发起支付请求时提示
{"code":"PARAM_ERROR","detail":{"location":null,"value":["/body/payer/openid"]},"message":"请求中含有未在API文档中定义的参数"}

**Comment by zlei669** [comment]
服务商jsapi支付文档
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter4_1_1.shtml

**Comment by Matrix-X** [comment]
you are right, thx for your issue!

pls check version v3.0.35

**Comment by zlei669** [comment]
您发给我的信件已经收到。
