### ISSUE TITLE
openWork代码问题

### ISSUE THREAD

**Issue by Kline-x** [ArtisanCloud/PowerWeChat#317]
请问openWork代码是对应什么的呢？企微第三方应用开发吗？现在openWork的代码时不能用的吗？

**Comment by Matrix-X** [comment]
谢谢，你的关注，暂时没有测试环境，代码有写，你可以加我们企业微信，可以进步一沟通

**Comment by Kline-x** [comment]
> 谢谢，你的关注，暂时没有测试环境，代码有写，你可以加我们企业微信，可以进步一沟通

![image](https://github.com/ArtisanCloud/PowerWeChat/assets/44720525/43ebea09-c823-4067-93e2-28ec394a0169)
代码都是报错的

**Comment by Matrix-X** [comment]
是的，就像我上面提到的，没有测试环境，只是一个rough的code。
这个调试排期会在后面

这里有一个不错的解决方案，有用户贡献PR，帮助实现开放平台的办法：https://github.com/ArtisanCloud/PowerWeChat/pull/309

如果你觉得你可以帮助我们调通openwork，欢迎你的PR
