### ISSUE TITLE
企业微信jssdk问题

### ISSUE THREAD

**Issue by Kline-x** [ArtisanCloud/PowerWeChat#318]
企业微信获取应用的jsapi_ticket也没有吗？
请求接口：https://qyapi.weixin.qq.com/cgi-bin/ticket/get?access_token=ACCESS_TOKEN&type=agent_config
文档接口：https://developer.work.weixin.qq.com/document/path/90506

**Comment by Matrix-X** [comment]
<img width="1138" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/80596769-69ab-4fec-b8ee-612e9f43b988">

<img width="405" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/4d983208-3037-404b-96ae-870444c48a2f">
 

pls try this

**Comment by Kline-x** [comment]
> https://developer.work.weixin.qq.com/document/path/90506

您这个是获取企业的jsapi_ticket
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/44720525/c7587f2f-fb9f-44aa-a5e8-798ddc86ec95)


我说的是获取应用的jsapi_ticket
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/44720525/d910bf0f-eeed-40b8-bd10-eb95eaa2bcf1)

**Comment by Matrix-X** [comment]
yes , u r correct
pls check v3.0.36

<img width="796" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/2fbaefd8-8996-4c05-9a21-564560f900ce">

<img width="660" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/b0f7211e-276c-4df9-985e-d280bb691fb3">

**Comment by waset** [comment]
@Matrix-X @xuyang404 

请问如何分别获取企业和应用的ticket？

是这样使用的吗？
<img width="612" alt="image" src="https://github.com/user-attachments/assets/1fe70265-21af-4105-bf58-d8c9a93c8f1f">

![image](https://github.com/user-attachments/assets/7106fb0e-30f4-485a-8226-90232e393b01)

**Comment by waset** [comment]
> @Matrix-X @xuyang404
> 
> 请问如何分别获取企业和应用的ticket？
> 
> 是这样使用的吗？
> ......

好像只有这样硬编码接口地址才能正确获取，并且生成缓存
<img width="722" alt="image" src="https://github.com/user-attachments/assets/53072864-f498-413c-873c-5071b9a91253">
<img width="404" alt="image" src="https://github.com/user-attachments/assets/5d934157-406e-41d8-b454-aad4cd792223">
