### ISSUE TITLE
微信门店是否有开发计划？

### ISSUE THREAD

**Issue by chunshengster** [ArtisanCloud/PowerWeChat#323]
接口文档：
https://developers.weixin.qq.com/doc/offiaccount/WeChat_Stores/WeChat_Store_Interface.html

**Comment by Matrix-X** [comment]
pls refer this : 

<img width="1356" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/60120167-e0b9-4481-808f-8f07fcfe40b7">

**Comment by Matrix-X** [comment]
如果不全，可以按照这个接口的样式规则，自己添加需要的接口，然后提交PR，谢谢

**Comment by chunshengster** [comment]
多谢
