### ISSUE TITLE
请问支付服务商商户进件的接口有吗？

### ISSUE THREAD

**Issue by chunshengster** [ArtisanCloud/PowerWeChat#325]
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter11_1_1.shtml

暂时没有查到

**Comment by Matrix-X** [comment]
这个服务商接口暂时没有支持到，如果你急着需要，请加企业微信，我可以把口子开好，你可以按照标准接口的方式，实现一下
