### ISSUE TITLE
是否有计划在"微信支付"的模块中增加对电子发票对应功能的支持？

### ISSUE THREAD

**Issue by susnow** [ArtisanCloud/PowerWeChat#332]
目前项目中遇到了需要开具发票的诉求 翻了翻文档似乎暂时还没有相关内容的支持

这个部分是否有支持的计划呢？

**Comment by Matrix-X** [comment]
官网的文档发来看看，我帮你确认一下接口

**Comment by susnow** [comment]
https://pay.weixin.qq.com/docs/merchant/apis/fapiao/fapiao-card-template/create-fapiao-card-template.html

这个部分相关的  创建模版, 开具电子发票等

**Comment by Matrix-X** [comment]
我提交了develop
先添加了一个ApplyForCardTemplate，请在这个分支上试一下这个接口

<img width="970" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/3e16ea5f-2fd9-4ddf-8781-d3e70742e253">

<img width="1127" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/2122ce59-bc11-4a93-bbd1-1e9daabae4a3">
