### ISSUE TITLE
OfficialAccount TagUsers参数问题

### ISSUE THREAD

**Issue by jili0819** [ArtisanCloud/PowerWeChat#356]
TagUsers(ctx context.Context, openIDs []string, tagID string)
tagID为int类型

**Comment by Matrix-X** [comment]
noted, thx!

Would you like to submit a pr if it's urgent for you?
Or I can fix it tonight if you can wait...

**Comment by Matrix-X** [comment]
pls check pls check v3.0.51
thx for ur pr!
