### ISSUE TITLE
有计划支持stable_token吗？

### ISSUE THREAD

**Issue by WongGinZoeng** [ArtisanCloud/PowerWeChat#377]
有计划支持stable_token吗？

**Comment by Matrix-X** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/getStableAccessToken.html

你是说这个全局token对吧

请加群讨论，我想了解一下你的使用场景

**Comment by YshadowZ** [comment]
请问这个后续有支持计划吗，相当于微信官方确保了并发安全和全局唯一，更健壮

**Comment by yu1ec** [comment]
@Matrix-X 请问，这块目前有支持吗？这个目前我这边开发时候有遇到的好处是可以将token缓存到本地环境，无论是文件还是内存，可以减少去查库的连接。
