### ISSUE TITLE
短剧媒资管理和小程序虚拟支付相关的接口有计划接入吗？

### ISSUE THREAD

**Issue by houseme** [ArtisanCloud/PowerWeChat#380]
[小程序虚拟支付](https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/industry/virtual-payment.html)

[短剧媒资管理](https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/industry/mini-drama/mini_drama.html)

@Matrix-X  感谢

**Comment by Matrix-X** [comment]
https://github.com/ArtisanCloud/PowerWeChat/blob/release/3.0.0/src/miniProgram/industry/miniDrama/vod/client.go

短剧媒体管理

**Comment by Matrix-X** [comment]
虚拟支付，下周有伙伴，应该会合并一个版本

**Comment by Matrix-X** [comment]
pls refer to : v3.0.63

feat(kernel): http post json support body with string

**Comment by Matrix-X** [comment]
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/317570/ff1ca55f-d8cb-4d15-9242-14e60517f7f1)


需要配置
AppKey
OfferID
