### ISSUE TITLE
小程序 scheme 码 query参数包含`&`时会出错

### ISSUE THREAD

**Issue by qcjackman** [ArtisanCloud/PowerWeChat#393]
```
wechat.MiniProgramApp.URLScheme.Generate(ctx, &request.URLSchemeGenerate{
    JumpWxa: &request.JumpWxa{
	    Path:       "pages/home/home",
	    Query:      "b=2&a=1&c=4",
	    EnvVersion: envVersion,
    },
    IsExpire:       false,
    ExpireType:     0,
    ExpireTime:     0,
    ExpireInterval: 0,
})
```

![image](https://github.com/ArtisanCloud/PowerWeChat/assets/12554120/491d51e1-1610-44e1-9136-b065f943ce1c)

版本信息：
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/12554120/bf9b3200-1c4a-4efe-bf14-b2e7b0b969ca)
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/12554120/c9375caf-904a-4d55-ac44-5d3dbcd25192)

**Comment by Matrix-X** [comment]
&符号被转义了，如果只是b=2,是可以过的，我们现在用的是 Path:       "pages/:parm1/:parm2",

**Comment by qcjackman** [comment]
> &符号被转义了，如果只是b=2,是可以过的，我们现在用的是 Path: "pages/:parm1/:parm2",

确实是被转义了，应该是 json.Marshal() 自动转义的吧，那这个有办法解决吗，比如暴露个配置项禁用默认转义呢？

**Comment by qcjackman** [comment]
> > &符号被转义了，如果只是b=2,是可以过的，我们现在用的是 Path: "pages/:parm1/:parm2",
> 
> 确实是被转义了，应该是 json.Marshal() 自动转义的吧，那这个有办法解决吗，比如暴露个配置项禁用默认转义呢？

像这位兄弟建议的这样
https://github.com/ArtisanCloud/PowerLibs/issues/81

**Comment by Matrix-X** [comment]
pls check v3.1.3, 

refact(http): add SetEscapeHTML false
