### ISSUE TITLE
小程序userConfig里Log配置的Driver不起作用

### ISSUE THREAD

**Issue by WongGinZoeng** [ArtisanCloud/PowerWeChat#396]
无论怎么设置，还是走的系统里的zap。

看MapUserConfig方法，里面根本就没设置driver？

**Comment by Matrix-X** [comment]
请问你是怎么设置的？

**Comment by Matrix-X** [comment]
<img width="883" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/45978f27-3639-4d19-8162-bd208976c125">
这里会去重载log driver，你可以试着debug跟一下，是否走入到

**Comment by WongGinZoeng** [comment]
> <img alt="image" width="883" src="https://user-images.githubusercontent.com/317570/270542415-45978f27-3639-4d19-8162-bd208976c125.png"> 这里会去重载log driver，你可以试着debug跟一下，是否走入到

看`src/miniProgram/application.go`里的`MapUserConfig`方法：
```
"log": &object.HashMap{
			"level": userConfig.Log.Level,
			"file":  userConfig.Log.File,
			"error": userConfig.Log.Error,
			"env":   userConfig.Log.ENV,
		},
```
对比公众号`src/officialAccount/application.go`里的`MapUserConfig`方法：
```
"log": &object.HashMap{
			"driver": userConfig.Log.Driver,
			"level":  userConfig.Log.Level,
			"file":   userConfig.Log.File,
			"error":  userConfig.Log.Error,
			"env":    userConfig.Log.ENV,
		},
```

明显小程序里就缺了driver，后面你再去`app.Config.Get("log.driver", nil)`肯定就get不到了。

**Comment by Matrix-X** [comment]
ok，小程序我看看

**Comment by Matrix-X** [comment]
请查看

[v3.1.5](https://github.com/ArtisanCloud/PowerWeChat/releases/tag/v3.1.5)

小程序和企业微信都补上了driver
