### ISSUE TITLE
微信小程序【Encryptor.DecryptData】 slice bounds out of range

### ISSUE THREAD

**Issue by caixukang** [ArtisanCloud/PowerWeChat#399]
我在 kratos 框架中 使用 powerwechat 解析用户手机号加密字符串，有时成功有时失败，以下是我失败时的错误提示，
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/32930007/ac9c0be7-15d6-461f-8df5-7bc72955c408)
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/32930007/f8375f72-3a98-4c7f-8165-7f4eaab30cda)
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/32930007/69ca1f59-db5c-4c2d-bd8f-b2b5c73a7d9a)

**Comment by Matrix-X** [comment]
加一下群吧，我和你直接沟通一下，这种随机问题，得需要配合联调
