### ISSUE TITLE
开放平台代授权调用微信接口失败

### ISSUE THREAD

**Issue by JessieKaa** [ArtisanCloud/PowerWeChat#402]
使用OpenPlatform.MiniProgram会自动调用微信accesstoken接口，此时由于传入的secret是开放平台的，接口必报错。
开放平台代授权调用微信接口不应该调用到微信获取accesstoken接口

**Comment by Matrix-X** [comment]
简易添加企业微信群，我帮你一起看看，报错信息和调度的参数
