### ISSUE TITLE
企业微信客服开发的文档不太好理解  没找到 OpenKfId 

### ISSUE THREAD

**Issue by mofadeyunduo** [ArtisanCloud/PowerWeChat#416]
https://powerwechat.artisan-cloud.com/zh/wecom/server.html#%E5%BC%80%E5%A7%8B%E6%8E%A5%E6%94%B6%E6%B6%88%E6%81%AF 
在这里怎么接收客服消息呢

我查到了事件是 CALLBACK_EVENT_KF_MSG_OR_EVENT 没看到对应结构体 我尝试搜索结构体 不应该有 OpenKfId 字段么，参考这个文档 https://developer.work.weixin.qq.com/document/path/90238#12977，没搜到如何读取 OpenKfId

**Comment by mofadeyunduo** [comment]
应该用什么
msg := models.？？？{}

![image](https://github.com/ArtisanCloud/PowerWeChat/assets/15816394/87f4c2e7-11a0-4c0c-ad58-8afb0f3ceb3c)
没有 
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/15816394/8414cf0a-6503-4d33-9684-9c1bd2a27753)
OpenKfId

**Comment by mofadeyunduo** [comment]
type RequestAccountServiceSendMsg struct {
	ToUser      string                              `json:"touser"`
	OpenKfid    string                              `json:"open_kfid"`
	MsgID       string                              `json:"msgid"`
	MsgType     string                              `json:"msgtype"`
	Text        RequestAccountServiceMsgText        `json:"text,omitempty"`
	Image       RequestAccountServiceMsgImage       `json:"image,omitempty"`
	Voice       RequestAccountServiceMsgVoice       `json:"voice,omitempty"`
	File        RequestAccountServiceMsgFile        `json:"file,omitempty"`
	Link        RequestAccountServiceMsgLink        `json:"link,omitempty"`
	MiniProgram RequestAccountServiceMsgMiniProgram `json:"miniprogram,omitempty"`
	Menu        RequestAccountServiceMsgMenu        `json:"msgmenu,omitempty"`
	Location    RequestAccountServiceMsgLocation    `json:"location,omitempty"`
}
这个发消息的对象是不是有点问题吧，应该是 *RequestAccountServiceMsgText，不然 omitempty 没用吧

**Comment by Matrix-X** [comment]
> type RequestAccountServiceSendMsg struct {
> ToUser string `json:"touser"`
> OpenKfid string `json:"open_kfid"`
> MsgID string `json:"msgid"`
> MsgType string `json:"msgtype"`
> Text RequestAccountServiceMsgText `json:"text,omitempty"`
> Image RequestAccountServiceMsgImage `json:"image,omitempty"`
> Voice RequestAccountServiceMsgVoice `json:"voice,omitempty"`
> File RequestAccountServiceMsgFile `json:"file,omitempty"`
> Link RequestAccountServiceMsgLink `json:"link,omitempty"`
> MiniProgram RequestAccountServiceMsgMiniProgram `json:"miniprogram,omitempty"`
> Menu RequestAccountServiceMsgMenu `json:"msgmenu,omitempty"`
> Location RequestAccountServiceMsgLocation `json:"location,omitempty"`
> }
> 这个发消息的对象是不是有点问题吧，应该是 *RequestAccountServiceMsgText，不然 omitempty 没用吧

你看到挺仔细，这个请查看最新的版本 : https://github.com/ArtisanCloud/PowerWeChat/tree/v3.1.13
已经追加了*

**Comment by Matrix-X** [comment]
> 应该用什么 msg := models.？？？{}
> 
> ![image](https://private-user-images.githubusercontent.com/15816394/285775192-87f4c2e7-11a0-4c0c-ad58-8afb0f3ceb3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwOTY2MzYsIm5iZiI6MTcwMTA5NjMzNiwicGF0aCI6Ii8xNTgxNjM5NC8yODU3NzUxOTItODdmNGMyZTctMTFhMC00YzBjLWFkNTgtOGFmYjBmM2NlYjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE0NDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNTc1NjJmNzM2MWVmMjcwZjNkYzVhY2M4OWFmOGIyM2EzNTRmMGVjYzVjMjU0Mzg2NTNkNTA2YWJmMDhmMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EvHkhrE4ZektGjnvdnfT2LLE9Le21Af2oLKTiWVRFd0) 没有 ![image](https://private-user-images.githubusercontent.com/15816394/285775338-8414cf0a-6503-4d33-9684-9c1bd2a27753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwOTY2MzYsIm5iZiI6MTcwMTA5NjMzNiwicGF0aCI6Ii8xNTgxNjM5NC8yODU3NzUzMzgtODQxNGNmMGEtNjUwMy00ZDMzLTk2ODQtOWMxYmQyYTI3NzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE0NDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4Y2QwM2EzZTMyMjUzNTk2NDk3YjVmOTAxOWU0YWViZDc2NmQ2OWM1NjVlNjVjYThiMDY4MjhlY2EyNmJlNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LWKH1C52-d8q6FNFnNxLb3bEXPjbUAHaMB2LFhaaGFo) OpenKfId


我新加了一个数据类型
<img width="838" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/5a733465-a1c6-4e8e-888e-1ad2c9cd66b1">


具体使用方法是：

通过GetEvent后，再通过定义个事件内容结构体，通过event.ReadMessage(&msg)去解析获取。
<img width="359" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/9ac96a51-134e-4a8e-8936-33a6a8ce735d">

我已经上传到develop分支了，请试着用一下，如果没问题，我可以打一个版本

如果有问题，请随时添加我的微信，我可以帮助协助

**Comment by mofadeyunduo** [comment]
> > type RequestAccountServiceSendMsg struct {
> > ToUser string `json:"touser"`
> > OpenKfid string `json:"open_kfid"`
> > MsgID string `json:"msgid"`
> > MsgType string `json:"msgtype"`
> > Text RequestAccountServiceMsgText `json:"text,omitempty"`
> > Image RequestAccountServiceMsgImage `json:"image,omitempty"`
> > Voice RequestAccountServiceMsgVoice `json:"voice,omitempty"`
> > File RequestAccountServiceMsgFile `json:"file,omitempty"`
> > Link RequestAccountServiceMsgLink `json:"link,omitempty"`
> > MiniProgram RequestAccountServiceMsgMiniProgram `json:"miniprogram,omitempty"`
> > Menu RequestAccountServiceMsgMenu `json:"msgmenu,omitempty"`
> > Location RequestAccountServiceMsgLocation `json:"location,omitempty"`
> > }
> > 这个发消息的对象是不是有点问题吧，应该是 *RequestAccountServiceMsgText，不然 omitempty 没用吧
> 
> 你看到挺仔细，这个请查看最新的版本 : https://github.com/ArtisanCloud/PowerWeChat/tree/v3.1.13 已经追加了*

主要是我在开发企业微信客服...此外帮忙检查一下这些对象吧，很多都是 optional 的，比如 	MsgID       string                               `json:"msgid"`，这个字段没加上 omitempty 传到微信会提示不合法的空字符串 msgid，必须要 omit 掉...

**Comment by Matrix-X** [comment]
pls check v3.1.15

帮你添加了omit for

type RequestAccountServiceSendMsg struct {
	ToUser      string                               `json:"touser"`
	OpenKfid    string                               `json:"open_kfid"`
	MsgID       string                               `json:"msgid,omitempty"`
	MsgType     string                               `json:"msgtype,omitempty"`
	Text        *RequestAccountServiceMsgText        `json:"text,omitempty"`
	Image       *RequestAccountServiceMsgImage       `json:"image,omitempty"`
	Voice       *RequestAccountServiceMsgVoice       `json:"voice,omitempty"`
	File        *RequestAccountServiceMsgFile        `json:"file,omitempty"`
	Link        *RequestAccountServiceMsgLink        `json:"link,omitempty"`
	MiniProgram *RequestAccountServiceMsgMiniProgram `json:"miniprogram,omitempty"`
	Menu        *RequestAccountServiceMsgMenu        `json:"msgmenu,omitempty"`
	Location    *RequestAccountServiceMsgLocation    `json:"location,omitempty"`
}

**Comment by mofadeyunduo** [comment]
thx 有空我就测一下 实在是太忙了

**Comment by mofadeyunduo** [comment]
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/15816394/f98fc65b-aada-4685-8731-981822004e26)
这个接口最后一个参数是选填...

**Comment by mofadeyunduo** [comment]
哦 抱歉 看到了 hashmap 结构你们过滤了

**Comment by Matrix-X** [comment]
> 哦 抱歉 看到了 hashmap 结构你们过滤了

no problem
