### ISSUE TITLE
希望能关闭日志输出

### ISSUE THREAD

**Issue by simondzw** [ArtisanCloud/PowerWeChat#419]
希望能配置输出什么级别的日志，或者直接关闭日志输出，能同步到控制台输出就更好了。
![1702449585886](https://github.com/ArtisanCloud/PowerWeChat/assets/153709598/e1c6400b-6d39-4c34-b315-b1102d8dc932)

**Comment by Matrix-X** [comment]
sorry for the late version v3.1.16

set Level: "error", to prevent the info message saved into log
