### ISSUE TITLE
微信支付配置优化。。。

### ISSUE THREAD

**Issue by sornian** [ArtisanCloud/PowerWeChat#427]
微信支付CertPath，KeyPath
等参数能否直接传入内容
而非路径。。

**Comment by Matrix-X** [comment]
pls check this

https://www.bilibili.com/video/BV1Yb4y137qP/?spm_id_from=333.1007.top_right_bar_window_history.content.click&vd_source=1d120f41ee7b1be77aa8cceff5d5628f

<img width="582" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/faef3bf2-986a-4d00-b9c5-d4a392f3ed86">
