### ISSUE TITLE
微信小程序无法获取小程序码

### ISSUE THREAD

**Issue by dalangll** [ArtisanCloud/PowerWeChat#430]
**1. 文档和真实调用写法不一致**
![201705389736_ pic](https://github.com/ArtisanCloud/PowerWeChat/assets/31510856/1f14dc5c-a767-4b12-a71d-5aba3a4905d7)
![211705389778_ pic](https://github.com/ArtisanCloud/PowerWeChat/assets/31510856/4e4f50ac-5a7a-4bad-9931-2f8e8b992be1)

**2. 调用后一直报错参数错误**
`{{"errcode":40097,"errmsg":"invalid args rid: 65a62f1d-4d9a17fb-628b69e0"}}
`

**Comment by Matrix-X** [comment]
是的，文档没有及时更新，这里新加了一个env_version参数，文档默认是"develop"
<img width="755" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/76507f73-caa1-4c01-a93e-e589dda7bd79">
请尝试添加一下这个参数

<img width="882" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/44d0037e-c0f2-49b7-a733-cdfb0b54f512">

**Comment by dalangll** [comment]
加了env_version参数后，已正常
