### ISSUE TITLE
无法获取小程序码

### ISSUE THREAD

**Issue by dalangll** [ArtisanCloud/PowerWeChat#431]
**官网文档如下：**
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/31510856/5ef7f899-dab3-4000-b4cf-e2467d472324)
**实际源码调用和文档不符：**
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/31510856/60fe03de-f3f5-4b26-9ade-ff81f97f930e)
按照源码调用后一直报错：
**报错内容为：微信服务器参数错误：**
{{"errcode":40097,"errmsg":"invalid args rid: 65b0d6c1-3504e8dd-732b509c"}}
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/31510856/2e2040d7-677a-4230-b194-1798bd136eeb)

**Comment by Matrix-X** [comment]
之前的issue，已经说明了
https://github.com/ArtisanCloud/PowerWeChat/issues/430


你现在输入envVersion为""

<img width="899" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/1cff005c-c607-45f9-9eec-f45ffc74670b">

请加上"develop"

**Comment by dalangll** [comment]
好的，我试试 之前的 issue我没看到了

**Comment by dalangll** [comment]
设置envVersion参数 为 develop后已经正常
