### ISSUE TITLE
ide无法正确识别嵌套方法

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [ArtisanCloud/PowerWeChat#439]
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/67987607/2b995566-0c8a-4f80-9ab8-ceffdfc6f580)

**Comment by Mr-Ao-Dragon** [comment]
其他包正常，唯独此框架不可用

**Comment by Matrix-X** [comment]
最好加一下我的微信，帮你看看，你这张截图，我没法很好的找出问题，初步看是你没下载PowerLib这个依赖库

**Comment by Mr-Ao-Dragon** [comment]
感谢您的回复！我通过rm -r .idea解决了问题

**Comment by Matrix-X** [comment]
ok, have fun!
