### ISSUE TITLE
JSSDK退款API调用时refund_out_no字段未写入到请求body中

### ISSUE THREAD

**Issue by AlvinQinwen** [ArtisanCloud/PowerWeChat#44]
- go version:  go1.16.7 darwin/amd64
- sdk version v1.1.5

调用退款接口
```go
paymentClient, err := utils.NewWXPaymentApp(ctx.Request, params.AppId, NotifyUrl)
	if err != nil {
		panic(err)
	}
	fmt.Println(params.RefundOutNO)
	// 1634095819-969073932
	outRefundNo := fmt.Sprintf("%d-%d", time.Now().Unix(), time.Now().Nanosecond())
	response, err := paymentClient.Refund.Refund("xxxxx", outRefundNo, &power.HashMap{
		"refund":   15,
		"total":    15,
		"currency": "CNY",
	}, &power.HashMap{
		"reason": "技术部退款",
	})

	fmt.Println(response)
```

根据`utils.NewWXPaymentApp()`方法中的`HttpDebug: true`可看到请求参数缺失**out_refund_no**
![image](https://user-images.githubusercontent.com/40420020/137081569-5c02e5c7-bb76-4060-ab65-c41ee91e937b.png)

以及api接口返回信息亦提示
**输入源“/body/out_refund_no”映射到字段“商户退款单号”必填性规则校验失败，此字段为必填项**
![image](https://user-images.githubusercontent.com/40420020/137081680-ef3d9439-417a-47b2-a733-46be3386b7e0.png)

**Comment by Matrix-X** [comment]
请升级使用 release 1.1.7，已经完成强类型对象，传参。
