### ISSUE TITLE
文档描述错误 微信支付->退款->退款接口

### ISSUE THREAD

**Issue by AlvinQinwen** [ArtisanCloud/PowerWeChat#45]
```go
paymentService.Refund.Refund(
  transactionID, // 微信支付单号
  refundOutNO, // 商户外部单号
  &object.HashMap{
    "refund": 1, // 退款金额。 必填
    "total": 1, // 总金额。 必填
    "currency": "CNY", // 目前微信只支持CNY
  }, 
  nil,
)
```

refundOutNO应为**自己生成的退款单号** 而**不是**商户下单号
![image](https://user-images.githubusercontent.com/40420020/137082586-217997ec-c093-44c5-889b-4611b5f434a3.png)
[jssdk退款文档](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_9.shtml)

**Comment by Matrix-X** [comment]
请升级使用 release 1.1.7，已经完成强类型对象，传参。
