### ISSUE TITLE
不支持商家转账批次回调通知吗？

### ISSUE THREAD

**Issue by miuchan** [ArtisanCloud/PowerWeChat#461]

**Comment by Matrix-X** [comment]
<img width="1346" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/7b9ea2ca-43b3-4b17-bc4b-34c16e381647">


和JSAPI支付通知一样，他们接受回调的结构是一样的，然后如果要read batch transfer的，用这个结构体去承接解密后的data

<img width="1292" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/aed03f00-1bf9-4a30-bee3-412656170377">
