### ISSUE TITLE
框架有自动更新平台证书吗？

### ISSUE THREAD

**Issue by miuchan** [ArtisanCloud/PowerWeChat#462]

**Comment by Matrix-X** [comment]
<img width="1324" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/3f68d727-a476-4879-b214-6e5f3add0a15">

现在只有获取接口的，如果要自动化，这个功能暂时得自己去实现。
因为没想明白怎么在SDK里如果要有一个比较节省资源的策略，去实现自动化。

如果有更方便的解决方案集成在SDK中，也欢迎来提PR
