### ISSUE TITLE
微信API请求类型错误

### ISSUE THREAD

**Issue by stardemo** [ArtisanCloud/PowerWeChat#472]
https://github.com/ArtisanCloud/PowerWeChat/blob/4aad29d919b22f66fcca054139ba94279ff76700/src/payment/transfer/batch.go#L107C61-L107C71
<img width="972" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/20634646/fd9ad102-7335-45df-a3c2-5d20a3ee1d23">

**Comment by Matrix-X** [comment]
ok, I’ll check it later

**Comment by Matrix-X** [comment]
pls check v3.2.10
