### ISSUE TITLE
小游戏虚拟支付功能可以接入吗

### ISSUE THREAD

**Issue by hezijia666** [ArtisanCloud/PowerWeChat#476]

**Comment by Matrix-X** [comment]
<img width="1304" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/ed5b600c-2fa6-470c-bc50-59d191c267f1">

check this module

**Comment by hezijia666** [comment]
有些字段不完善，可以提merge合并吗，一般多久会合并
