### ISSUE TITLE
“获取应用的jsapi_ticket”这个接口，文档里写的需要参数access_token，为什么函数里不传这个参数？

### ISSUE THREAD

**Issue by Lanmon94** [ArtisanCloud/PowerWeChat#487]
<img width="1052" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/43365518/a42223c0-b4e4-46ce-ae95-978666fd0c19">

<img width="1560" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/43365518/e455b12d-de73-46db-9edf-8aa02bdbb98a">

**Comment by Matrix-X** [comment]
access_token是所有接口都会要会要传的，所以sdk封装了而且缓存了access token，你不需要考虑传送ac，只要把app id和app secret设置正确就行了。可以到redis到缓存数据库中查找你的ac

**Comment by Lanmon94** [comment]
好的，谢谢🙏

**Comment by Matrix-X** [comment]
welcome to star our project ,thx

**Comment by Lanmon94** [comment]
这项目真的不错，很好用，这么少star不应该呀，应该有上百k star才对。

**Comment by Matrix-X** [comment]
项目起的晚，多帮着推荐，谢谢
