### ISSUE TITLE
weComService.MiniProgram()报错

### ISSUE THREAD

**Issue by cKeygn** [ArtisanCloud/PowerWeChat#498]
win11 x64
go 1.22.3
通讯录管理没问题，但是企业微信小程序初始化一直报错，报错具体信息如下：
API server listening at: 127.0.0.1:52798
=== RUN   TestName
--- FAIL: TestName (0.00s)
panic: interface conversion: interface is nil, not contract.LoggerInterface [recovered]
	panic: interface conversion: interface is nil, not contract.LoggerInterface

goroutine 19 [running]:
testing.tRunner.func1.2({0xca56e0, 0xc00036fb90})
	C:/Program Files/Go/src/testing/testing.go:1631 +0x49e
testing.tRunner.func1()
	C:/Program Files/Go/src/testing/testing.go:1634 +0x669
panic({0xca56e0?, 0xc00036fb90?})
	C:/Program Files/Go/src/runtime/panic.go:770 +0x136
github.com/ArtisanCloud/PowerWeChat/v3/src/kernel.(*AccessToken).RegisterHttpMiddlewares(0xc0001e6630)
	D:/Go_Modules/pkg/mod/github.com/!artisan!cloud/!power!we!chat/v3@v3.2.18/src/kernel/accessToken.go:343 +0x1fb
github.com/ArtisanCloud/PowerWeChat/v3/src/kernel.NewAccessToken(0xc000380f90)
	D:/Go_Modules/pkg/mod/github.com/!artisan!cloud/!power!we!chat/v3@v3.2.18/src/kernel/accessToken.go:78 +0x5a8
github.com/ArtisanCloud/PowerWeChat/v3/src/work/auth.NewAccessToken({0xdb6468, 0xc00037de78})
	D:/Go_Modules/pkg/mod/github.com/!artisan!cloud/!power!we!chat/v3@v3.2.18/src/work/auth/accessToken.go:16 +0xaa
github.com/ArtisanCloud/PowerWeChat/v3/src/work/miniProgram.NewApplication(0xc00035e930, {0x0, 0x0, 0x0})
	D:/Go_Modules/pkg/mod/github.com/!artisan!cloud/!power!we!chat/v3@v3.2.18/src/work/miniProgram/application.go:53 +0x53a
github.com/ArtisanCloud/PowerWeChat/v3/src/work.(*Work).MiniProgram(0xc000378000)
	D:/Go_Modules/pkg/mod/github.com/!artisan!cloud/!power!we!chat/v3@v3.2.18/src/work/application.go:561 +0x118
go-zero-single-serve/common/wechatx/com.(*Client).Session(0xc000370240, {0xd46b6e, 0x6})
	F:/go-zero-single-recycle/go-zero-single-serve/common/wechatx/com/client.go:53 +0x10d
go-zero-single-serve/common/wechatx/com.TestName(0xc0001f3520)
	F:/go-zero-single-recycle/go-zero-single-serve/common/wechatx/com/client_test.go:10 +0x87
testing.tRunner(0xc0001f3520, 0xd81d28)
	C:/Program Files/Go/src/testing/testing.go:1689 +0x1da
created by testing.(*T).Run in goroutine 1
	C:/Program Files/Go/src/testing/testing.go:1742 +0x7d3

Debugger finished with the exit code 0

**Comment by Matrix-X** [comment]
初始化代码发一下

好像是log没有设置好
panic: interface conversion: interface is nil, not contract.LoggerInterface [recovered]

**Comment by johnsongs** [comment]
weComApp, err := work.NewWork(&work.UserConfig{
		CorpID:    cfg.MustGet(ctx, "wechat.CorpID").String(),      // 企业微信的app id，所有企业微信共用一个。
		AgentID:   cfg.MustGet(ctx, "wechat.AgentID").Int(),        // 内部应用的app id
		Secret:    cfg.MustGet(ctx, "wechat.WecomSecret").String(), // 内部应用的app secret
		HttpDebug: cfg.MustGet(ctx, "wechat.HttpDebug").Bool(),
		Debug:     cfg.MustGet(ctx, "wechat.isDebug").Bool(),
		OAuth: work.OAuth{
			Callback: "***", //
			Scopes:   nil,
		},
		Cache: kernel.NewRedisClient(&kernel.UniversalOptions{
			Addrs:    []string{cfg.MustGet(ctx, "wechat.Cache.Addr").String()},
			Password: cfg.MustGet(ctx, "wechat.Cache.Password").String(),
			DB:       cfg.MustGet(ctx, "wechat.Cache.DB").Int(),
		}),
	})
weComApp这样初始化的，不知道为什么在后续调用获取小程序的时候miniApp, err := weComApp.MiniProgram()已知报着相同错误，调试最后抱错位置在accessToken.go文件中344行logger := (*accessToken.App).GetComponent("Logger").(contract2.LoggerInterface)。
版本：github.com/ArtisanCloud/PowerWeChat/v3 v3.2.44
