### ISSUE TITLE
似乎依赖版本有问题

### ISSUE THREAD

**Issue by zsq2010** [ArtisanCloud/PowerWeChat#499]
go: github.com/ArtisanCloud/PowerWeChat/v3@v3.2.18 requires
	github.com/ArtisanCloud/PowerSocialite/v3@v3.0.7 requires
	github.com/ArtisanCloud/PowerLibs/v3@v3.0.3 requires
	github.com/golang-module/carbon@v1.5.5: reading github.com/golang-module/carbon/go.mod at revision v1.5.5: unknown revision v1.5.5

github.com/golang-module/carbon@v1.5.5这个已经没了

**Comment by Matrix-X** [comment]
你是在什么情况下出现这个问题的？
能否加微信聊？

**Comment by xuesongtao** [comment]
<img width="1249" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/43270497/d3ceff3e-83bf-442c-8713-22bb187e9be1">
用不了啊

**Comment by Matrix-X** [comment]
我本地试试

**Comment by Matrix-X** [comment]
<img width="1486" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/1e8eaeb8-830f-4c61-b9ff-8b0e6933e071">

我这里启动服务都正常，需要你们提供更多信息，是怎么一个用不了的场景，请截图更多信息，或者加我微信，我可以远程协助hbj418

BTW go 1.21

**Comment by Matrix-X** [comment]
> go: github.com/ArtisanCloud/PowerWeChat/v3@v3.2.18 requires github.com/ArtisanCloud/PowerSocialite/v3@v3.0.7 requires github.com/ArtisanCloud/PowerLibs/v3@v3.0.3 requires github.com/golang-module/carbon@v1.5.5: reading github.com/golang-module/carbon/go.mod at revision v1.5.5: unknown revision v1.5.5
> 
> github.com/golang-module/carbon@v1.5.5这个已经没了


<img width="827" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/e0511cf6-93a6-4879-a346-a22e5b64d9f3">

github.com/golang-module/carbon v1.6.0

**Comment by xuesongtao** [comment]
![image](https://github.com/ArtisanCloud/PowerWeChat/assets/43270497/5438cea2-a2f7-4fdd-aa19-f48d27bd5c1f)
现在安装好了，我开始安装了多次都报相同错误  net/http: TLS handshake timeout

**Comment by Matrix-X** [comment]
> ![image](https://private-user-images.githubusercontent.com/43270497/335993154-5438cea2-a2f7-4fdd-aa19-f48d27bd5c1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDM4MjgsIm5iZiI6MTcxNzQwMzUyOCwicGF0aCI6Ii80MzI3MDQ5Ny8zMzU5OTMxNTQtNTQzOGNlYTItYTJmNy00ZmRkLWFhMTktZjQ4ZDI3YmQ1YzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA4MzIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYjIwNTQ3NjlhNTVhNTNkNTViN2QyNzNiMTA3M2I3OGUxMTZlYjhlMjQ5NWM0NjdkMzUyZGYxYWIyNTg4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XjKitTCXu8e1RBidUjagW9S2XceW4rLozrBLMXxGTGw) 现在安装好了，我开始安装了多次都报相同错误 net/http: TLS handshake timeout

这个应该是网络原因，没法下载这个版本的包

**Comment by xuesongtao** [comment]
好的
