### ISSUE TITLE
请求企业微信接口的时候是否支持 http 代理？

### ISSUE THREAD

**Issue by stormeyes** [ArtisanCloud/PowerWeChat#501]
现在请求企业微信的接口都需要经过企业的可信 IP，目前框架是否支持配置 http 代理，发出的请求都走配置的企业可信 IP 为 代理 IP 的场景呢？

**Comment by Matrix-X** [comment]
请查看源码：https://github.com/ArtisanCloud/PowerWeChat/blob/release/3.2.0/src/kernel/baseClient.go

<img width="838" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/67bd26c2-2fda-408e-98d2-4c11c585b586">


<img width="1066" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/e0608c41-7439-48d2-a071-078976b6465c">

试试这个参数

**Comment by stormeyes** [comment]
试过了，这个参数确实可以实现代理，感谢

**Comment by Matrix-X** [comment]
不谢，欢迎star
