### ISSUE TITLE
企业微信 AddMomentTask 发布朋友圈这个方法返回数据结构问题

### ISSUE THREAD

**Issue by Childbird** [ArtisanCloud/PowerWeChat#505]
https://developer.work.weixin.qq.com/document/path/95095   

发布朋友圈，返回的数据结构是，
{
	"errcode":0,
	"errmsg":"ok",
	"jobid":"xxxx"
}

但是项目中用的返回数据结构是：
type ResponseAddMomentTask struct {
	response.ResponseWork
	Status int    `json:"status"`
	Type   string `json:"type"`
	Result Result `json:"result"`
}
这个应该是 获取任务创建结果  对应的结构。

**Comment by Matrix-X** [comment]
感谢你的issue，我已经调整了提交到develop分之了，https://github.com/ArtisanCloud/PowerWeChat/tree/develop

另外我还追加了GetMomentTaskResult接口

请尝试使用一下，如果没问题，我就合并升级版本，谢谢！

**Comment by Childbird** [comment]
谢谢，辛苦您了，但是我们这边测试可能得一阵子，一时半会可能没法给您回复效果，相信您调整的没问题

**Comment by Matrix-X** [comment]
那请用v3.2.21，等你空了可以使用一下，有问题再沟通
