### ISSUE TITLE
升级到最新版后发生了goruntine泄露

### ISSUE THREAD

**Issue by wangrizhao** [ArtisanCloud/PowerWeChat#507]
升级到最新版后程序发生了协程泄露，原因是最新版中依赖了gopkg.in/natefinch/lumberjack.v2库，pprof看到是这个库创建了大量协程，然后我降级到v3.0.22这个现象消失了

**Comment by Matrix-X** [comment]
可能是zap实用了这个库，导致的问题：https://github.com/natefinch/lumberjack/issues/56

我看看是否可以升级到他们的稳定版本

**Comment by Matrix-X** [comment]
我在看rotatelogs这个日志文件的轮转方案，来替换lumberjack.v2。我在出差，等晚点我试试。同步给你

<img width="945" alt="image" src="https://github.com/ArtisanCloud/PowerWeChat/assets/317570/b083d145-6db6-4050-8367-92d5b898c951">

**Comment by Matrix-X** [comment]
我按照社区里 https://github.com/natefinch/lumberjack/pull/57/files 的讨论，改造了一下lumberjack的代码，封装在PowerLib里。

请尝试使用PowerWechat  [develop](https://github.com/ArtisanCloud/PowerWeChat/tree/develop)，在你的环境中再测试一下。

如果没问题，我再打一个版本。

**Comment by Matrix-X** [comment]
pls view [v3.2.22](https://github.com/ArtisanCloud/PowerWeChat/releases/tag/v3.2.22)
