### ISSUE TITLE
官网打不开了?

### ISSUE THREAD

**Issue by qcjackman** [ArtisanCloud/PowerWeChat#523]
https://powerwechat.artisan-cloud.com/

![image](https://github.com/user-attachments/assets/1c3118b1-2c60-46c9-a6c5-b884c832834c)

**Comment by runlabs** [comment]
me too

**Comment by Matrix-X** [comment]
不好意思，腾讯云的cdn被刷了。
现在应该好了，我用另外的方案部署了，同时用了最新的vitepress，请过目
