### ISSUE TITLE
小程序：消息解密(services.MiniProgramApp.Server.Notify) xml格式时报错：plain is to small 2；json格式报错：EOF

### ISSUE THREAD

**Issue by huoxiao001** [ArtisanCloud/PowerWeChat#524]
报错：plain is to small 2，原因还没有排查到。

json格式报错EOF，看起来是因为结构体定义未支持json格式，导致解析json失败。

![截屏2024-07-31 22 57 24](https://github.com/user-attachments/assets/e47aff7b-70fd-42a2-9c42-ff60f71d53c2)

还没有研究透彻，不确定是否会有其它影响，就先不提交PR了😅

**Comment by Matrix-X** [comment]
你回调通知的，用的是xml还是json？

**Comment by huoxiao001** [comment]
> 你回调通知的，用的是xml还是json？

现在是json格式的。xml格式现在也调不通

**Comment by huoxiao001** [comment]
今天又把回调通知格式改成了xml。服务器上仍报错：plain is to small 2。然后在本地使用微信在线工具调试，就出现了如下截图的情况 在线工具：(https://developers.weixin.qq.com/apiExplorer?type=messagePush)

![image](https://github.com/user-attachments/assets/f1b7c726-b6da-459e-af92-806c61a34f10)

使用微信在线工具中的 "请求构造" ，拿里面的发送包体和请求URI，在本地测试 xml格式，正常；"调试工具" 中 拿里面的发送包体和请求URI，在本地测试 xml格式，就也是报错：plain is to small 2。

看了微信官方给的解密demo，这个解密逻辑和官方的解密逻辑也没看出区别在哪..

**Comment by huoxiao001** [comment]
微信官方文档中要求：EncodingAESKey 尾部填充一个字符的 "="
_下面是文档的解密部分截图：_
![image](https://github.com/user-attachments/assets/493fce23-7b3b-48a3-b3f3-9df8be3bd74c)

我在配置文件中加了 = ，测试效果和上面一样，仍是 请求构造 的没问题，调试工具 的失败。

**Comment by Matrix-X** [comment]
这个我觉得还是加微信聊吧，我们需要看到更多的信息
