### ISSUE TITLE
请问下哪个方法可以获取到小程序的名字

### ISSUE THREAD

**Issue by Rulessly** [ArtisanCloud/PowerWeChat#537]

**Comment by Matrix-X** [comment]
这是一个灵魂的拷问，我好像不记得微信有这个接口，你能在微信官网上找到这个获取小程序名称的接口么？

**Comment by Rulessly** [comment]
https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/basic-info-management/getAccountBasicInfo.html

POST https://api.weixin.qq.com/cgi-bin/account/getaccountbasicinfo?access_token=ACCESS_TOKEN 好像是这个吧

**Comment by Rulessly** [comment]
我初始化了miniProgram.MiniProgram，但这个方法在包中是放到了openPlatform/authorizer下，不知道要怎么才能去调用

**Comment by Rulessly** [comment]
没事了，已解决

**Comment by Matrix-X** [comment]
> https://developers.weixin.qq.com/doc/oplatform/openApi/OpenApiDoc/miniprogram-management/basic-info-management/getAccountBasicInfo.html
> 
> POST https://api.weixin.qq.com/cgi-bin/account/getaccountbasicinfo?access_token=ACCESS_TOKEN 好像是这个吧

<img width="1433" alt="image" src="https://github.com/user-attachments/assets/0cf2acc2-7542-44dc-a2f1-cb3bb70a5b23">
