### ISSUE TITLE
日志输出中可否增加链路追逐相关字段，方便排查问题

### ISSUE THREAD

**Issue by linganmin** [ArtisanCloud/PowerWeChat#539]
类似下面这种，取ctx中的trace信息输出

{"@timestamp":"2024-09-04T16:16:11.465+08:00","caller":"handler/loghandler.go:147","content":"[HTTP] 200 - GET /admin/store/supplier/product/list?page=1&size=20&store_id=&product_id=&supplier_id= - 222.92.150.50 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36","duration":"5.9ms","level":"info","span":"c1b44cc0c15758b0","trace":"02ed1f83f01175af269d3bc0321b7aca"}

**Comment by Matrix-X** [comment]
应该可以，我空了看看怎么加上去，如果你急也可以提PR

**Comment by linganmin** [comment]
> 应该可以，我空了看看怎么加上去，如果你急也可以提PR

好的，我最近也是在赶项目 等过两周忙完如果您没时间加我就pr一下

**Comment by Matrix-X** [comment]
主要是看PowerLib里的LogInterface，可能加一个参数，tracing，然后看看zap driver是否支持这个参数。

**Comment by linganmin** [comment]
> 主要是看PowerLib里的LogInterface，可能加一个参数，tracing，然后看看zap driver是否支持这个参数。

👌🏻

**Comment by Matrix-X** [comment]
Thank you for you PR, pls check v3.2.42

**Comment by linganmin** [comment]
> Thank you for you PR, pls check v3.2.42

可以了，感谢
