### ISSUE TITLE
初始化代码发一下

### ISSUE THREAD

**Issue by johnsongs** [ArtisanCloud/PowerWeChat#551]
初始化代码发一下

好像是log没有设置好
panic: interface conversion: interface is nil, not contract.LoggerInterface [recovered]

_Originally posted by @Matrix-X in https://github.com/ArtisanCloud/PowerWeChat/issues/498#issuecomment-2138825967_

**Comment by johnsongs** [comment]
weComApp, err := work.NewWork(&work.UserConfig{
CorpID: cfg.MustGet(ctx, "wechat.CorpID").String(), // 企业微信的app id，所有企业微信共用一个。
AgentID: cfg.MustGet(ctx, "wechat.AgentID").Int(), // 内部应用的app id
Secret: cfg.MustGet(ctx, "wechat.WecomSecret").String(), // 内部应用的app secret
HttpDebug: cfg.MustGet(ctx, "wechat.HttpDebug").Bool(),
Debug: cfg.MustGet(ctx, "wechat.isDebug").Bool(),
OAuth: work.OAuth{
Callback: "***", //
Scopes: nil,
},
Cache: kernel.NewRedisClient(&kernel.UniversalOptions{
Addrs: []string{cfg.MustGet(ctx, "wechat.Cache.Addr").String()},
Password: cfg.MustGet(ctx, "wechat.Cache.Password").String(),
DB: cfg.MustGet(ctx, "wechat.Cache.DB").Int(),
}),
})
weComApp这样初始化的，不知道为什么在后续调用获取小程序的时候miniApp, err := weComApp.MiniProgram()一直报着相同错误，调试最后报错位置在accessToken.go文件中344行logger := (*accessToken.App).GetComponent("Logger").(contract2.LoggerInterface)。
版本：github.com/ArtisanCloud/PowerWeChat/v3 v3.2.44

**Comment by Matrix-X** [comment]
```go
Log: work.Log{
	Level:  "debug",
	File: "./wechat.log",
        Stdout: false, //  是否打印在终端

}
```

需要直接补上

**Comment by Matrix-X** [comment]
https://powerwechat.artisan-cloud.com/zh/wecom/

**Comment by johnsongs** [comment]
呃 我补上了但还是报错，我发现问题是不是出在miniprogram/application.go中，这个文件中有一个GetComponent方法没有返回logger

**Comment by Matrix-X** [comment]
加我微信聊吧

**Comment by johnsongs** [comment]
A18663970177

**Comment by johnsongs** [comment]
**问题描述：**
我这里报错的步骤是初始化weComApp, err := work.NewWork后获取weComApp.MiniProgram()时发生错误
**环境：**
IDE：VSCODE
Go：1.23
**解决方式：**
昨天咱俩讨论之后，我在调试过程中并未发现app不是application的情况，我在测试过程中主要追踪到

```
src/kernel/accessToken.go
config := (*accessToken.App).GetConfig()。【正常执行】
logger := (*accessToken.App).GetComponent("Logger").(contract2.LoggerInterface)。    【panic】
```

这两行代码只有下面的部分是panic的。如果传进来的app有问题，那第一行config应该也是取不到对应方法，所以我不清楚是不是咱俩的IDE不同导致。我这里是用的是VSCODE提供的调试模块。
追踪后发现在src/work/miniProgram/application.go的GetComponent中并未正常返回Logger，加上之后我这里正常运行。

原始代码:

```
src/work/miniProgram/application.go Line:78
func (app *Application) GetComponent(name string) interface{} {

	switch name {
	case "Base":
		return app.Base
	case "AccessToken":
		return app.AccessToken
	case "Auth":
		return app.Auth
	case "Config":
		return app.Config

	default:
		return nil
	}

}
```

**Comment by Matrix-X** [comment]
pls check v3.2.45
