### ISSUE TITLE
payment.UserConfig 中的 CertPath 和 KeyPath  可不可以新增直接设置证书内容的 配置字段，使用者直接读取证书内容

### ISSUE THREAD

**Issue by lukeyMing** [ArtisanCloud/PowerWeChat#555]
payment.UserConfig 可不可以新增直接设置证书内容的 配置字段，使用者直接读取证书内容

`// 从文件中读取
certContent, _ := os.ReadFile("./cert.pem")
keyContent, _ := os.ReadFile("./key.pem")

// 从go-bindata 打包的文件中读取

// 从数据库中读取...

payment.UserConfig{
CertContent: certContent,
KeyContent:  keyContent,
}`

**Comment by Matrix-X** [comment]
这个字段也兼容文件中的问本期内容

**Comment by lukeyMing** [comment]
> CertContent: certContent,
> KeyContent: keyContent,

感谢
