### ISSUE TITLE
企业微信获取小程序结构报错

### ISSUE THREAD

**Issue by coldsmirk** [ArtisanCloud/PowerWeChat#566]
```go
(*work.Work).MiniProgram() // 执行报 nil 强转 cache.CacheInterface 的错误
```
<img width="1887" alt="image" src="https://github.com/user-attachments/assets/94c16e63-25c0-4359-8d0e-620167ab125a">

这里我实例化 work.Work 结构是这样的：
```go
work.NewWork(&work.UserConfig{
		Log: work.Log{
			Driver: new(logger),
			Level:  "info",
			ENV:    "production",
		},
		OAuth: work.OAuth{
			Callback: "https://www.ilxqx.com/callback",
		},
		CorpID:  config.Viper.GetString("wechat.work.mini_app.corp_id"),
		AgentID: config.Viper.GetInt("wechat.work.mini_app.agent_id"),
		Secret:  config.Viper.GetString("wechat.work.mini_app.secret"),
	})
```
很明显我没有传 Cache 属性，文档说了，不传走内存，我不需要用Redis等其他缓存：
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/c05bdd2a-bf6d-4ea0-96fc-e4847b2aa917">

源码中直接没有判断拿到的值是否为 nil 就直接强转（咋敢的呢😂😂） `config.Get("cache", nil).(cache.CacheInterface)`

还有一个问题：
```go
OAuth: work.OAuth{
			Callback: "https://www.ilxqx.com/callback",
		}
```
这个必须要传 Callback，很显然我用不到 OAuth 相关的东西，参数校验强制我传就有点不合理了吧。

**Comment by Matrix-X** [comment]
pls check v3.2.51
