### ISSUE TITLE
为什么公众号的网页授权是跳转 https://open.weixin.qq.com/connect/qrconnect 这个地址

### ISSUE THREAD

**Issue by anhao** [ArtisanCloud/PowerWeChat#568]

**Comment by Matrix-X** [comment]
你指一下，你认为的地址是哪儿个？引一下微信文档的出处

**Comment by anhao** [comment]
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html

不应该是 https://open.weixin.qq.com/connect/oauth2/authorize 吗

通过实例化公众号OfficialAccount Oauth 获取的跳转地址是 qrconnect 的

**Comment by Matrix-X** [comment]
“为什么公众号的网页授权是跳转 ”你是看到哪儿，问到这个问题？

**Comment by Matrix-X** [comment]
https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Wechat_Login.html

这个是开放平台的接口

**Comment by anhao** [comment]
https://powerwechat.artisan-cloud.com/zh/official-account/oauth.html
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html

公众号的网页授权，不是开发平台的

是需要自己手动拼接链接吗

**Comment by Matrix-X** [comment]
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/375a6e68-cccd-4c9f-842b-329a27e7104b">

**Comment by Matrix-X** [comment]
加微信沟通吧，加群沟通
