### ISSUE TITLE
由于cache缓存的access_token，引发的生成小程序码问题

### ISSUE THREAD

**Issue by GnezIew** [ArtisanCloud/PowerWeChat#580]
在小程序上更换了小程序码的图片，导致原有的access_token已经失效，而由于cache的工作机制的问题，导致在没过期之前一直使用的是已经失效的access_token进行请求的。

**Comment by Matrix-X** [comment]
这个问题还是加群聊吧，我得知道为什么会更新换小程序码的图片，会导致access token失效，同时如果cache的token失效，会自动刷新新的token，可以继续使用
