### ISSUE TITLE
是否支持proxy代理配置呢

### ISSUE THREAD

**Issue by Ocyss** [ArtisanCloud/PowerWeChat#597]
需要配置ip白名单，而直接使用ssh进行代理转发会方便很多

搜索代码是有个配置，但不清楚如何配置
```
	proxyURI := config.GetString("http.proxy_uri", "")
```

**Comment by Matrix-X** [comment]
可以下载v3.3.2版本

<img width="712" alt="image" src="https://github.com/user-attachments/assets/7f5a2210-9e77-408c-8237-7a0b8476e46d" />

在初始化对象的时候，可以在Http这个参数项添加proxy

kernel里有处理proxy uri

<img width="728" alt="image" src="https://github.com/user-attachments/assets/173c4cc6-1cc4-4054-a0ff-cc0652680367" />


如有问题可以添加微信沟通
