### ISSUE TITLE
RedPack Info接口参数tarType可去掉

### ISSUE THREAD

**Issue by WalleV** [ArtisanCloud/PowerWeChat#6]
![CleanShot 2021-09-05 at 12 21 55@2x](https://user-images.githubusercontent.com/10766933/132115207-82523df6-0918-4a44-abc3-e32a9296f382.png)

如图tarType声明但未使用，建议去掉。

文件路径： `src/payment/redpack/client.go`

**Comment by Matrix-X** [comment]
已去除

"{payment} - remove redpack.info unused parameters"
