### ISSUE TITLE
企业微信内部应用OAuth授权bug list

### ISSUE THREAD

**Issue by WalleV** [ArtisanCloud/PowerWeChat#65]
1. 使用简单版的返回`user, err := WeComApp.OAuth.Provider.ContactFromCode(code)`, `user.GetID()`可以正确返回值。但是如果使用详细版`user, err := WeComApp.OAuth.Provider.Detailed().ContactFromCode(code)`，里面`user.GetID()`获取到的为空。
2. `user.GetRaw()`会抛错`interface {} is object.HashMap, not *object.HashMap`。
3. `GetAuthURL()`之前需要全局设置`WithRedirectURL(callbackUrl)`，这个在网络请求存在并发的情况下可能导致callbackUrl冲突。
4. 授权的时候`redirect_uri`需要被urlencode编码，不然在一些带有特殊字符的情况下导致OAuth2重定向调整出错。

**Comment by Matrix-X** [comment]
已修复
