### ISSUE TITLE
Order.Unify目前只支持JSAPI，需要支持扫码支付功能

### ISSUE THREAD

**Issue by WalleV** [ArtisanCloud/PowerWeChat#8]
目前只实现了[JSAPI](https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_4.shtml)。

还有以下未实现：
 - [APP支付](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_2_1.shtml)
 - [H5支付](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_3_1.shtml)
 - [Native支付](https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_4_1.shtml)

**Comment by Matrix-X** [comment]
35dc7f9..63e54ac  feature/payment -> feature/payment

 {payment} - split unfiy pay transcation into jssdk app native h5 ...
