### ISSUE TITLE
企业微信发送消息增加默认填充agentid

### ISSUE THREAD

**Issue by WalleV** [ArtisanCloud/PowerWeChat#9]
问题原因： 企业微信里面每次发送消息是需要`agentid`的。

解决方案： sdk里面可以判断如果用户没有填充`agentid`，那就走初始化时候的`agentid`。

微信文档地址： [https://open.work.weixin.qq.com/api/doc/90000/90135/90236](https://open.work.weixin.qq.com/api/doc/90000/90135/90236)

**Comment by Matrix-X** [comment]
初始化的依据是什么？

**Comment by Matrix-X** [comment]
{work-message} - change send interface to power.hashmap"
